### ISSUE TITLE
SystemTreeViewItem is hard to be used

### ISSUE THREAD

**Issue by sinall** [mwinapi/mwinapi#4]
SystemTreeViewItem has only 'Children' and 'Title', which makes it's hard to be used.
I was expecting HTREEITEM to do further work. Thanks.

**Comment by schierlm** [comment]
Pull requests are welcome :-)

Also, perhaps additionally to adding a getter for the Handle, add methods that actually do your "further work".

**Comment by sinall** [comment]
Just let you know, I'm going with a different approach now. After around 1000 lines of DllImport and message definition had been written, I decided to use C++/CLI which make the code more clear.

**Comment by schierlm** [comment]
I'll close this issue then :)
